import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import React from "react";
import Providers from "@/lib/providers/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="icon" href="/icon.ico" />
      <link
        rel="stylesheet"
        type="text/css"
        charSet="UTF-8"
        href="/css/slick.min.css"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="/css/slick-theme.min.css"
      />
      <title>Blood Bank</title>
    </head>
    <body>
    <Providers>
      <AppRouterCacheProvider>
        <>
          <Toaster position={"top-center"} />
          {children}
        </>
      </AppRouterCacheProvider>
    </Providers>
    </body>
    </html>
  );
}
