import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import React from "react";
import Providers from "@/lib/providers/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <Providers>
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <>
          <Toaster position={"top-center"} />
          {children}
        </>
      </AppRouterCacheProvider>
      </body>
    </html>
      </Providers>
  );
}
